#pragma once

#define BATTERY_INDICATOR_START_INDEX 1
#define BATTERY_INDICATOR_END_INDEX   5

#define BLE_INDICATOR_PREFIX
#define BLE_SLOT_1_INDICATOR 1
#define BLE_SLOT_2_INDICATOR 2
#define BLE_SLOT_3_INDICATOR 3
#define BLE_SLOT_4_INDICATOR 4

#define BLE_INDICATOR_PREFIX
#define ESB_INDICATOR 5
