#pragma once

#define BATTERY_INDICATOR_START_INDEX 1
#define BATTERY_INDICATOR_END_INDEX   5

#define BATTERY_INDICATOR_POSITIVE_COLOR_R 0x1F
#define BATTERY_INDICATOR_POSITIVE_COLOR_G 0x0E
#define BATTERY_INDICATOR_POSITIVE_COLOR_B 0xFF
#define BATTERY_INDICATOR_MEDIAL_COLOR_R   0x59
#define BATTERY_INDICATOR_MEDIAL_COLOR_G   0xFF
#define BATTERY_INDICATOR_MEDIAL_COLOR_B   0xF5
#define BATTERY_INDICATOR_NEGATIVE_COLOR_R 0xFF
#define BATTERY_INDICATOR_NEGATIVE_COLOR_G 0x00
#define BATTERY_INDICATOR_NEGATIVE_COLOR_B 0x00

#define BLE_INDICATOR_PREFIX
#define BLE_SLOT_1_INDICATOR 1
#define BLE_SLOT_2_INDICATOR 2
#define BLE_SLOT_3_INDICATOR 3
#define BLE_SLOT_4_INDICATOR 4

#define BLE_INDICATOR_PREFIX
#define ESB_INDICATOR 5
