#pragma once

enum {
    RESERVED_ = 0x0,
    WHITELIST_EEPROM_START_POSITION_ = 0x400,
    USER_EEPROM_START_POSITION_ = 0x500,
    QMK_EEPROM_START_POSITION_ = 0x6000,
    BLE_EEPROM_START_POSITION_ = 0x7C00,
};

#define WHITELIST_EEPROM_START_POSITION WHITELIST_EEPROM_START_POSITION_
#define USER_EEPROM_START_POSITION      USER_EEPROM_START_POSITION_
#define QMK_EEPROM_START_POSITION       QMK_EEPROM_START_POSITION_
#define BLE_SNV_ADDR                    BLE_EEPROM_START_POSITION_
