// Copyright 2023 Y&R-Biu (@jiaxin96)
// SPDX-License-Identifier: GPL-2.0-or-later

// RB_PIN_UART0  -  UART0: PB4/PB7 ->  PA15/PA14
// #define UART0_IO_REMAPPING

// RB_PIN_UART1  -  UART1: PA8/PA9 ->  PB12/PB13
// #define UART1_IO_REMAPPING

// RB_PIN_UART2  -  UART2: PA6/PA7 ->  PB22/PB23
// #define UART2_IO_REMAPPING

// RB_PIN_UART3  -  UART3: PA4/PA5 ->  PB20/PB21
// #define UART3_IO_REMAPPING

/* I2C_IO_REMAPPING    -  I2C: PB13/PB12 -> PB21/PB20 */
// #define I2C_IO_REMAPPING

/* SPI_IO_REMAPPING   -  SPI0:  PA12/PA13/PA14/PA15 -> PB12/PB13/PB14/PB15 */
// #define SPI_IO_REMAPPING

// #define BLE_TX_POWER LL_TX_POWEER_MINUS_16_DBM
// #define BLE_TX_POWER LL_TX_POWEER_MINUS_12_DBM
// #define BLE_TX_POWER LL_TX_POWEER_MINUS_8_DBM
// #define BLE_TX_POWER LL_TX_POWEER_MINUS_5_DBM
// #define BLE_TX_POWER LL_TX_POWEER_MINUS_3_DBM
// #define BLE_TX_POWER LL_TX_POWEER_MINUS_1_DBM
// #define BLE_TX_POWER LL_TX_POWEER_0_DBM
// #define BLE_TX_POWER LL_TX_POWEER_1_DBM
// #define BLE_TX_POWER LL_TX_POWEER_2_DBM
#define BLE_TX_POWER LL_TX_POWEER_3_DBM
// #define BLE_TX_POWER LL_TX_POWEER_4_DBM
// #define BLE_TX_POWER LL_TX_POWEER_5_DBM
// #define BLE_TX_POWER LL_TX_POWEER_6_DBM
