include_directories(${CMAKE_CURRENT_LIST_DIR}/BLE_LIB
    ${CMAKE_CURRENT_LIST_DIR}/HAL/include
    ${CMAKE_CURRENT_LIST_DIR}/LWNS
    ${CMAKE_CURRENT_LIST_DIR}/printf
    ${CMAKE_CURRENT_LIST_DIR}/RVMSIS
    ${CMAKE_CURRENT_LIST_DIR}/StdPeriphDriver/inc
    ${CMAKE_CURRENT_LIST_DIR}/USB_LIB
)

file(GLOB_RECURSE CH582_SOURCES
    "${CMAKE_CURRENT_LIST_DIR}/HAL/*.c"
    "${CMAKE_CURRENT_LIST_DIR}/printf/*.c"
    "${CMAKE_CURRENT_LIST_DIR}/RVMSIS/*.c"
    "${CMAKE_CURRENT_LIST_DIR}/StdPeriphDriver/*.c"
    "${CMAKE_CURRENT_LIST_DIR}/USB_LIB/*.c"
)
list(REMOVE_ITEM CH582_SOURCES
    "${CMAKE_CURRENT_LIST_DIR}/StdPeriphDriver/CH58x_usbdev.c"
    "${CMAKE_CURRENT_LIST_DIR}/HAL/SLEEP.c"
)
list(APPEND CH582_SOURCES
    "${CMAKE_CURRENT_LIST_DIR}/Startup/startup_CH583_APP.S"
)

file(GLOB_RECURSE CH582_IAP_SOURCES
    "${CMAKE_CURRENT_LIST_DIR}/HAL/*.c"
    "${CMAKE_CURRENT_LIST_DIR}/printf/*.c"
    "${CMAKE_CURRENT_LIST_DIR}/RVMSIS/*.c"
    "${CMAKE_CURRENT_LIST_DIR}/StdPeriphDriver/*.c"
    "${CMAKE_CURRENT_LIST_DIR}/USB_LIB/*.c"
)
list(APPEND CH582_IAP_SOURCES
    "${CMAKE_CURRENT_LIST_DIR}/Startup/startup_CH583_IAP.S"
)

set(LINKER_SCRIPT_APP ${CMAKE_CURRENT_LIST_DIR}/Ld/Link_APP.ld)
set(LINKER_SCRIPT_IAP ${CMAKE_CURRENT_LIST_DIR}/Ld/Link_IAP.ld)
set(CH582_LIB
    ${CMAKE_CURRENT_LIST_DIR}/StdPeriphDriver/libISP583.a
    ${CMAKE_CURRENT_LIST_DIR}/BLE_LIB/LIBCH58xBLE.a
    ${CMAKE_CURRENT_LIST_DIR}/USB_LIB/libRV3UFI.a
)
